hybridauth/hybridauth

README.md
=> Fix: Sourceforge redirects to GitHub anyway

additional-providers/hybridauth-vkontakte/Providers/Vkontakte.php
Here's the request object:
```
"PHP message: stdClass Object
(
[access_token] => 80...
[expires_in] => 86400
[user_id] => 1
[email] => me@example.com
)"
```
So there's no ```user_email```...
=> Fixed an issue with email property for vkontakte

additional-providers/hybridauth-steam/Providers/Steam.php
Hi!
I've added Steam API support for user data retrieving to Steam OpenID provider.
Actually, it's just a little modified/refactored version of Steam provider from 3.0.0 branch of HybridAuth project.
I don't know why this patch exists only in 3.0.0 version, but I think it needs to be in current stable version too.
=> Steam API user data support

hybridauth/Hybrid/Endpoint.php
Changed static methods to dynamic, also constructor added.
`::process` method left for backward-compatibility and calls constructor.
Should not break any existing code using this according to documentation.
Also big question whether we need all that methods and properties to be public?
=> Make Hybrid_Endpoint methods non-static

hybridauth/Hybrid/thirdparty/LinkedIn/LinkedIn.php
Problem: sometimes LinkedIn API requests take forever, so the PHP process is blocked waiting for a response. But we don't want to run into timeouts on our end, so we can simply restrict the timeout and HybridAuth will deal with potential errors appropriately :-)
=> Set LinkedIn API request timeout to 5 seconds because the API can be slow.

hybridauth/Hybrid/Providers/Google.php
This seemed to be a missing logic. I needed it for https://www.drupal.org/project/hybridauth project to have several identities and merge Google account with existing account on Drupal by verified email
=> Adding emailVerified for Google email type 'account'

hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php
Fix for serious bug introduced in https://github.com/hybridauth/hybridauth/commit/bf9fb5efb9ac770ded293f799ca4063fb8369df4#diff-9b114ab1ce86b49dbe086cbf8ace8391R147.
Decoded JSON data before return were replaced back by encoded, in particular, Vkontakte failed to work because of this (Facebook worked anyway though).
=> Fix for serious OAuth2 bug in 2.4.0 release!

src/Adapter/OpenID.php
Fixes missing use statement for an exception called in the OpenID adapter.
=> Missing OpenID use statement

src/Adapter/AbstractAdapter.php, src/Adapter/OAuth1.php, src/Adapter/OpenID.php, src/Hybridauth.php, src/Thirdparty/OAuth/OAuthRequest.php, src/Thirdparty/OpenID/LightOpenID.php
Related to https://github.com/hybridauth/hybridauth/pull/464#issuecomment-98987814.
This is what php-cs-fixer did:
```bash
~/projects/fork/hybridauth(3.0.0-Remake)$ php vendor/bin/php-cs-fixer fix --verbose --level=psr2 .
F.F..................................................F.................FF.F............
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
1) src/Thirdparty/OpenID/LightOpenID.php (visibility)
2) src/Thirdparty/OAuth/OAuthRequest.php (visibility)
3) src/Hybridauth.php (single_line_after_imports)
4) src/Adapter/AbstractAdapter.php (single_line_after_imports)
5) src/Adapter/OAuth1.php (single_line_after_imports)
6) src/Adapter/OpenID.php (single_line_after_imports)
Fixed all files in 18.646 seconds, 12.000 MB memory used
```
=> Apply CS fixer for PSR-2

composer.json
Just a composer requirements improve to allow getting latest PHPUnit 4 versions.
Note: `4.6` is the latest version.
=> Less restrictive phpunit dependency

hybridauth/Hybrid/Auth.php
Sometimes session was not saved before doing a fast redirect (we use nginx/php5-fpm), should fix this issue #340 also.
=> Ensure session is saved before sending response

additional-providers/hybridauth-vkontakte/Providers/Vkontakte.php
1. Now you can use HybridAuth config to set fields that will be taken from [VKontakte](https://vk.com/) for [users.get](https://vk.com/dev/users.get) and [friends.get](https://vk.com/dev/friends.get)
2. Refactor code to use api_base_url from \OAuth2Client
=> Move Vkontakte fields to configuration

src/HttpClient/Util.php
According to [PHP documentation](https://php.net/manual/en/reserved.variables.server.php):
> 'HTTPS'
> Set to a non-empty value if the script was queried through the HTTPS protocol.
> Note: Note that when using ISAPI with IIS, the value will be off if the request was not made through the HTTPS protocol.
That is why we just need to check whether `$_SERVER['HTTPS'] ` exists and is not `off`.
Also equality changed to strict one.
=> Simplification of `HybridAuth\HttpClient\Util::getCurrentUrl()`

src/Adapter/AbstractAdapter.php, src/HttpClient/Curl.php, src/HttpClient/Guzzle.php, src/Hybridauth.php, src/Logger/Logger.php, src/Logger/LoggerInterface.php, src/Logger/Psr3LoggerWrapper.php
Since we are trying to keep Hybridauth standalone, PSR3 logger interface was not includes into source code. This would cause problems when Composer's version will be used with Hybridauth and will make bundled autoloader much more complex.
That is why bundled logger interface is only forward-compatible with PSR3 logger interface.
What does this mean? Well, it contains some of methods from PSR3's Logger interface with exactly the same names and set/type of arguments.
While this is great, PHP doesn't allow you to inject some object that doesn't directly (or by some of its parents) implement required method, which makes it impossible to inject PSR3 loggers directly.
For Composer we'll use dummy logger interface that will extend `\Psr\Log\LoggerInterface` and thus will be also compatible with …
=> PSR3 logger

src/HttpClient/Util.php
* HHVM under HTTP sets `$_SERVER['HTTPS']` to empty string
* Existing check is redundant since it is a part of `Collection::get()` method already
=> HHVM HTTP fix

hybridauth/Hybrid/Logger.php
The previous version of Logger.php was not compatible with older versions of PHP (my server runs 5.3.3, for reasons beyond my control). It gave this error:
PHP Parse error:  syntax error, unexpected T_OBJECT_OPERATOR, expecting ')' in     
.../hybridauth/hybridauth/Hybrid/Logger.php on line 44
(and again on lines 63 and 81)
This fix simply changes that "(new DateTime)->format(DATE_ATOM)" to two separate lines in order to work, but it has exactly the same functionality. I have tested it and it works.
Hybridauth is awesome! Thanks for such a great tool.
=> rewrite syntax into an equivalent way that is compatible with older PHP

hybridauth/Hybrid/Providers/LinkedIn.php
When trying to login with Linkedin, if I refused the permission, I would get the following PHP notice:
<pre>
Undefined index: oauth_token
/home/foobar/shared/common/lib/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Providers/LinkedIn.php(62)
</pre>
return url:
https://www.foo.bar/site/oauth?hauth%2Edone=LinkedIn&oauth_problem=user_refused
=> Undefined index: oauth_token notice in Linkedin provider

src/Provider/Facebook.php
Facebook changed profile data requests to provide the minimal of name and id. Without specifying the fields HybridAuth uses it'll only have those two for their profile data. This fixes it to request the fields used by HybridAuth specifically.
=> [Facebook] Fixes getUserProfile v2.4 compatibility

additional-providers/hybridauth-vkontakte/Providers/Vkontakte.php
This method doesn't consider that user can have empty fields as 'country' and 'city'. So there are will be two warnings.
=> Fix warnings for getUserByResponse() in Vkontakt provider.

hybridauth/Hybrid/Logger.php
this error is caused by DateTime settings. please add this to your code
Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are required to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /home2/markewl7/public_html/guildgear/system/library/Hybrid/Logger.php:80 Stack trace: #0 /home2/markewl7/public_html/guildgear/system/library/Hybrid/Logger.php(80): DateTime->__construct() #1 /home2/markewl7/public_html/guildgear/system/library/Hybrid/Endpoint.ph …
=> DateTime error

hybridauth/Hybrid/Provider_Model_OAuth1.php
I had problems with the following combination :
Drupal + Drupal HybridAuth + Drupal OAuth + HybridAuth because OAuthConsumer class is already provided within Drupal OAuth.
=> Callback from linkedin and twitter lead to this error message : 
```
PHP Fatal error:  Cannot redeclare class OAuthConsumer in /var/www/sites/domain/sites/all/modules/oauth/lib/OAuth.php on line 20
```
@see : https://www.drupal.org/node/2147429
=> Require OAuth.php only if not exist

hybridauth/Hybrid/Endpoint.php
This PR enhances error reporting done by Hybrid_Endpoint. It replaces the default "Oophs. Error!" exception message with a more meaningful one and enables nested exception to be logged.
=> [Hybrid_Endpoint] Improve error reporting

additional-providers/hybridauth-odnoklassniki/Providers/Odnoklassniki.php
This PR improves error handling within Odnoklassniki provider. Sometimes $response returned from curl is false and thus doesn't contain 'error' property. This leads to log messages in the software I maintain like this: 
>User profile request failed! Odnoklassniki returned an error: exception 'ErrorException' with message 'Undefined property: stdClass::$error
So, I propose to improve error handling in this provider with this PR.
=> [odnoklassniki] Improve error reporting

hybridauth/Hybrid/thirdparty/OpenID/LightOpenID.php
There was no cURL connection and execution timeout in Hybrid OpenID
implementation. This can cause processes to wait ‘indefinitely’ for
a response.
=> Add cURL timeouts for OpenID

hybridauth/Hybrid/Providers/Facebook.php
For current facebook api (v2.5) read_stream permission is deprecated and not available for new apps. This means that facebook login cannot be used for new sites. (More info here: https://developers.facebook.com/docs/apps/versions)
=> Facebook login read_stream deprecated for 2.5

hybridauth/Hybrid/Logger.php, hybridauth/Hybrid/Providers/Facebook.php, hybridauth/Hybrid/Providers/Foursquare.php, hybridauth/Hybrid/Providers/Google.php, hybridauth/Hybrid/Providers/LinkedIn.php, hybridauth/Hybrid/Providers/Live.php, hybridauth/Hybrid/Providers/Twitter.php, hybridauth/Hybrid/Providers/Yahoo.php
With this PR I propose to improve HybridAuth logging and error reporting by the following:
- Where appropriate, propagate nested exception
- Where appropriate, output actual server response in "invalid response"-like messages to make debugging easier.
=> Improve logging and error handling in main providers

additional-providers/hybridauth-bitbucket/Providers/BitBucket.php
The URL to fetch email was changed in version 2 of the API, thus no email was returned. This fixes it.
=> Fix fetch email from new BitBucket API

hybridauth/Hybrid/Provider_Adapter.php
If after a successful login a user pushes the back button on his browser, the redirect in Auth.php gets called but the url passed to it is null because it was removed from the session after the user was logged in, the end result being a blank page.
=> Fixes redirect in auth after user pushes the browser back button

additional-providers/hybridauth-bitbucket/Providers/BitBucket.php
This echo statement shouldn't be here.  If someone wants to echo something they can get the data from the function since it returns it.  It shouldn't be in the core files.  It was added in 081ce1a9500c53e5fc00db23574040a9374ced62 and merged into master b203c4d5e2ad6400e36adbb1c94627d8fe3da63f .
=> Update bitbucket - take out unnecessary echo

additional-providers/hybridauth-sina/thirdparty/Sina/Sina.php
One of these expressions can be removed, unless it was supposed to be `https`?
=> Duplicate conditional expression in Sina.php

hybridauth/Hybrid/Endpoint.php
Feel free to merge my request, it fixes annoying notice when new HYBRID_ENDPOINT is spawned.
This issue happens when using XING Provider.
=> Fix PHP Notice when $_SERVER["QUERY_STRING"] is not defined.

hybridauth/Hybrid/Providers/Twitter.php
If an e-mail address is returned by Twitter, it's considered verified as per their documentation of the verify_credentials endpoint.
=> Set emailVerified for Twitter provider

hybridauth/Hybrid/Providers/LinkedIn.php
Shorthand arrays are PHP 5.4+, however the rest of this lib seems to be aimed for 5.2+, so I've replace the shorthand version with the usual `array()`.
=> Remove array shorthand constructor from LinkedIn provider

composer.json, hybridauth/Hybrid/Auth.php, hybridauth/Hybrid/Provider_Adapter.php, hybridauth/live.php
A while ago, Microsoft enforced their oauth security by disallowing redirect url to contain any parameters.
Hence the following redirect url does not work:
http://mywebsite.com/path_to_hybridauth/?hauth.done=Live
A workaound created by @tohweesiang was to provide another redirect url format in the case of Live authentication, so the redirect url will become like:
http://mywebsite.com/path_to_hybridauth/live.php
If this pull request is accepted than [Hybridauth's documentation for Windows Live](http://hybridauth.sourceforge.net/userguide/IDProvider_info_Live.html) should be changed as well,
regards
=> Workaround for Windows Live authentication

hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php
This OAuth2Client class is now compliant with the RFC6749 specifications (https://tools.ietf.org/html/rfc6749#section-2.3.1) regarding POST requests.
=> Fixed Google now enforcing application/x-www-form-urlencoded content

hybridauth/Hybrid/Provider_Model_OAuth2.php
Do not pass whole exception object as a message because it contains execution stack which
is sensitive information.
=> Fixed error message delivery

hybridauth/Hybrid/Providers/Facebook.php
The region info does not always have the same amount of info. That means
the index $regionArr[1]  is not always the country. I changed it to
fetch the last value of the array wich will most surely be the country.
=> [Facebook] Fix wrong country data

hybridauth/Hybrid/thirdparty/LinkedIn/LinkedIn.php
Fixes:
Fatal error: Cannot unset $this in /var/www/html2/anytimecaring/vendor/hybridauth/hybridauth/hybridauth/Hybrid/thirdparty/LinkedIn/LinkedIn.php on line 178
=> [LinkedIn] Removed unset() which breaks PHP 7.1 compatibility

hybridauth/Hybrid/Auth.php, hybridauth/Hybrid/Providers/Facebook.php
PR with fix for #698. Works well in both cases (composer and non-composer installation of Facebook SDK)
=> Fix fatal error during Facebook provider initialization (both for composer and non composer installation)

.travis.yml, composer.json, phpcs.xml
I've added the actual coding standards based on PSR2 that this library is coded after. If accepted we could fix some of the coding standard issues quite easily with `phpcbf`
=> Added actual coding standards

src/autoload.php
I added 2 `DIRECTORY_SEPARATOR`'s because:
1. Makes it compatible with windows server
(I use linux server, but test everything at home with EasyPHPServer on Windows and people might use IIS in general too)
2. I'm not sure if this was a bug or typically windows again, but it seems that `__DIR__ `doesn't have a trailing directory separator, so we have to add one. If this is not the same on linux, the latter case some more coding needs to be done on the first `DIRECTORY_SEPARATOR` not to be doubled for linux
=> autoload - Windows & slash forgot?

.travis.yml, additional-providers/hybridauth-disqus/Providers/Disqus.php, additional-providers/hybridauth-draugiem/Providers/Draugiem.php, additional-providers/hybridauth-draugiem/thirdparty/Draugiem/DraugiemApi.php, additional-providers/hybridauth-dribbble/Providers/Dribbble.php, additional-providers/hybridauth-dropbox/Providers/Dropbox.php, additional-providers/hybridauth-murmur/Providers/Murmur.php, additional-providers/hybridauth-pixnet/Providers/Pixnet.php, additional-providers/hybridauth-sina/thirdparty/Sina/Sina.php, additional-providers/hybridauth-sina/thirdparty/Sina/saetv2.ex.class.php, additional-providers/hybridauth-slack/Providers/Slack.php, additional-providers/hybridauth-stackexchange/Providers/StackExchange.php, additional-providers/hybridauth-steam/Providers/Steam.php, additional-providers/hybridauth-strava/Providers/strava.php, additional-providers/hybridauth-stripe/Providers/Stripe.php, additional-providers/hybridauth-wordpress/Providers/WordPress.php, additional-providers/hybridauth-xuite/Providers/Xuite.php
Now, every Travis CI build to branch v2 failed, because of wrong coding standards in some files and not supported php 5.3 by facebook/graph-sdk.
1. This PR fixes Coding Standards by running:
`phpcbf --standard=phpcs.xml additional-providers hybridauth`
2. This PR fixes an error with `facebook/graph-sdk requires PHP 5.4`
It's from travis-ci logs:
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- facebook/graph-sdk 5.5.0 requires php ^5.4|^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
- facebook/graph-sdk 5.4.4 requires php ^5.4|^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
- facebook/graph-sdk 5.4.3 requires php ^5.4|^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.
- facebook/graph-sdk …
```
=> Fix Travis CI build (fix phpcs and remove php 5.3)

hybridauth/Hybrid/Provider_Model.php
There are two calls of protected methods `loginFinish()` and `loginBegin()` in class Hybrid_Endpoint which not extends Hybrid_Provider_Model class.
It's fix #783
=> Make protected abstract methods (loginBegin, loginFinish) as public ones

additional-providers/hybridauth-stripe/Providers/Stripe.php
For Stripe it's possible to define what type of auth window to show initially - login or register.
Currently Hybridauth library does not allow to pass such parameter.
Add support of stripe_landing option for Stripe oauth callback.
See Stripe API for details (search by 'stripe_landing' word):
https://stripe.com/docs/connect/reference
=> [Stripe] Add optional stripe_landing auth parameter

additional-providers/hybridauth-steam/Providers/Steam.php
* Addition
Prevent broken authorization
Steam responds with HTTP/500 instead of xml from time to time, so we should handle exceptions thrown in SimpleXML to prevent broken authorization
=> [Steam] Fix broken authorization

src/Adapter/OAuth2.php
Added an if condition to ensure the access token does exist in the data store / session before adding it to request parameters.
Not having this condition actually broke my implementation.
Harmless code change. Please merge.
cc @StorytellerCZ @miled
=> Ensure the access_token exist in the dataStore

src/Provider/Facebook.php
Enable app secret proof for increase security
[Doc](https://developers.facebook.com/docs/graph-api/securing-requests#appsecret_proof)
Patch for #794
=> Add appsecret_proof for Facebook

src/Adapter/OAuth1.php, src/Adapter/OAuth2.php
After parsing by Data\Parser, result could be an array. Not always an object
=> apiRequest() sometimes return array hence this PHPDoc change

docs/providers.md, src/Provider/Authentiq.php
This PR adds support for Authentiq: A new OAuth2/OIDC provider that offers passwordless authentication and keeps personal data on the phone instead of in the cloud.
* New provider
=> Add Authentiq OAuth2/OIDC provider

additional-providers/hybridauth-authentiq/Providers/Authentiq.php
This PR adds support for Authentiq (to HybridAuth v2): A new OAuth2/OIDC provider that offers passwordless authentication and keeps personal data on the phone instead of in the cloud.
* New provider
=> Add Authentiq OAuth2/OIDC provider for HybridAuth v2

src/Provider/Google.php
* Patch for Google provider
Need R/O access to Gmail contacts
If I need R/O access to Gmail contacts, I have to specify scope https://www.googleapis.com/auth/contacts.readonly (https://developers.google.com/google-apps/contacts/v3/), but then I can't get this data via $google->getUserContacts() call. Either getGmailContacts has to be public, or we need to update getUserContacts method to support this R/O scope as well. I provided update for the second case.
Thanks!
=> Support R/O scope for Gmail contats as well

src/Provider/Vkontakte.php
without setting $scape='email' function getProfile doesn't return field email from vkontakte oauth2 service
(select one:)
* Addition
bug fix
=> vkontakte doesn't return email field on getProfile call

additional-providers/hybridauth-openstreetmap/Providers/OpenStreetMap.php
* New provider
Addition of OpenStreetMap authentication against v2 branch
I've added OpenStreetMap authentication on wordpress plugin, and thought it would be better to add it on hybridauth git repository instead of wordpress-social-login. I've only tested the plugin through Wordpress.
=> Add provider for OpenStreetMap, using OAuth 1.0a

src/Adapter/AbstractAdapter.php, src/Adapter/AdapterInterface.php, src/Adapter/OAuth1.php, src/Adapter/OAuth2.php, src/Provider/Facebook.php
Resolves #910 
It also improves a pages support on Hybridauth Provider level. For now, only Facebook provider supports post to pages. Later it can be improved for LinkedIn with Companies, etc..
=> Provide a setPageStatus for facebook

composer.json, tests/Data/CollectionTest.php, tests/Data/ParserTest.php, tests/HybridauthTest.php, tests/Storage/SessionTest.php, tests/User/ActivityTest.php, tests/User/ContactTest.php, tests/User/ProfileTest.php
Use `PHPUnit\Framework\TestCase` instead of `PHPUnit_Framework_TestCase`.
(select one:)
* Addition
This will help us when migrating to PHPUnit 6, that are now namespaced.
Use `PHPUnit\Framework\TestCase` instead of `PHPUnit_Framework_TestCase` while extending TestCases.
Just need to bump into [PHPUnit 4.8.35](https://github.com/sebastianbergmann/phpunit/blob/4.8/ChangeLog-4.8.md#4835---2017-02-06) that supports this namespace.
=> Use PHPUnit\Framework\TestCase instead of PHPUnit_Framework_TestCase

docs/providers.md, src/Provider/SteemConnect.php
* New provider
This feature enables login with [steemconnect](https://steemconnect.com/) for Steem Ecosystem.
Now, it can be used for login with steem and get user data.
=> SteemConnect provider integration

src/Provider/Google.php
(select one:)
* Addition
My client only want profile pictures larger then 480px. This pull request makes the image size of the google provider configurable.
I took the same method as the Facebook provider. Thus adding a photo_size to the config array enables you to change the image size.
=> make google image size configurable like facebook

src/Provider/LinkedIn.php
(select one:)
* Addition
The original picture url is in most cases larger than the linkedIn profile picture. This PR uses the config file to request the original picture url.
Caveat: The original picture url dimensions is not always square. 
Add `photo_size => 'original'` to the linkedIn config array to use this.
=> use linkedin original url as profile url

src/Adapter/OAuth1.php
For now, doesn't matter if you use `key` or `id` in HA config (both are valid).
=> Improve initialize of OAuth1 provider

src/Provider/Instagram.php
Instagram URL did not expose profileUrl, this PR addresses that.
=> return profileURL in Instagram adapter

src/Provider/Vkontakte.php
| Fixed Issues?            | fix #963  
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
for obtaining profile data, access_token is required
correct check on the server response containing the error was added
=> Fix Vkontakte provider for get profile data

hybridauth/Hybrid/Providers/LinkedIn.php
Addresses https://github.com/hybridauth/hybridauth/issues/988
| Fixed Issues?            | #988
| Minor: New Feature?      | No, just bug fix (stricter CSRF protection in force at LinkedIn
This fix is based on the code for the QQ provider: https://github.com/hybridauth/hybridauth/blob/v2/additional-providers/hybridauth-qq/Providers/QQ.php#L56-L71
=> Add "state" parameter to LinkedIn Provider

src/Provider/MicrosoftGraph.php
| Patch: Bug Fix?          | Yes. ` Uncaught Error: Call to undefined method stdClass::get() in /vendor/hybridauth/hybridauth/src/Provider/MicrosoftGraph.php:87`
Bug fix for the MicrosoftGraph provider.
=> Map response to Data\Collection object to use the get method

src/Provider/Tumblr.php
| Fixed Issues?            | `Wrong Tumblr endpoints`  
Updates the endpoints of the Tumblr provider as described in https://www.tumblr.com/docs/en/api/v2 and issue #980. Http was used, but changed to https.
Hopefully I'm doing this in the right way.
=> update tumblr endpoints

src/Provider/Blizzard.php, src/Provider/BlizzardAPAC.php, src/Provider/BlizzardEU.php
| Fixed Issues?            | None
| Major: Breaking Change?  | Yes
Blizzard have opened up their new developer portal, and the old one will be discontinued on January 6, 2019. More information can be found [here](https://us.battle.net/forums/en/bnet/topic/20769317376), but the gist of it is that the base URL is changing, as well as the route for fetching the authenticated user's information has changed. Also, app developers will need to set up new app credentials on a regular Battle.net account.
I have already implemented these changes at work, and they are getting the job done for our Battle.net login. However, for this upstream …
=> Update Blizzard provider to work with their new API

src/Provider/Steam.php
| Fixed Issues?            |  
When authenticating with steam, ->identifier may have https in and will not omit the url, giving the entire url instead of just the steam64id
=> Fixed $userProfile->identifier https issue

src/Provider/Yandex.php
| Fixed Issues?            |  No
Added Yandex provider for v3 for #1013
=> Added Yandex provider

src/Provider/Facebook.php
| Patch: Bug Fix?          | Kind of
Implemented fallback for Facebook to always have profile URL set on the identity user returned from the API. After sometime, Facebook stopped returning `link` from the API, so that the profile URL became empty.
=> Facebook profile URL fallback

README.md, docs/developer-ref-user-authentication.md
| Fixed Issues?            | Update docs
| Patch: Bug Fix?          | -
``` php
Fatal error: Uncaught TypeError: Argument 1 passed to Hybridauth\Adapter\AbstractAdapter::setApiEndpoints() must be an instance of Hybridauth\Data\Collection, array given
```
=> setApiEndpoints() must be an instance of Hybridauth\Data\Collection

README.md, hybridauth/Hybrid/Auth.php, hybridauth/Hybrid/Providers/Facebook.php
| Fixed Issues?            | Fixes #1056
| Major: Breaking Change?  | [x] 
| Minor: New Feature?      | [x]
BC: If you still use v2.8, it's recommended upgrade to at least v2.12 of Graph API.
See https://developers.facebook.com/docs/graph-api/changelog/
btw, if you still want to use own version of Graph API, you can do it via Hybridauth config - `default_graph_version`.
e.g 
```php
$config = [
"base_url" => "http://mywebsite.com/path/to/hybridauth/",
"providers" => [
"Facebook" => [
"enabled" => true,
"default_graph_version" => "PUT_YOURS_HERE", // e.g v3.0
"keys"    => [
"id" => "PUT_YOURS_HERE", 
"secret" => "PUT_YOURS_HERE",
],
],
],
];
```
=> Issue #1056: Upgrade facebook graph version to v2.12

src/Provider/Facebook.php
| Fixed Issues?            | Fixes #1056
| Major: Breaking Change?  | [x] 
| Minor: New Feature?      | [x]
BC: If you still use v2.8, it's recommended upgrade to at least v2.12 of Graph API.
See https://developers.facebook.com/docs/graph-api/changelog/
=> Upgrade facebook graph version to v2.12

src/Provider/Yahoo.php
| Fixed Issues?            | `Fixed Yahoo provider` 
Fixed Yahoo provider not returning e-mails, added proper scope for returning firstname/lastname/e-mail. 'sdps-r' doesn't return much useful information except uid, nickname and avatar.
=> Yahoo provider fix for firstname/lastname/e-mail

src/Adapter/OAuth1.php
| Fixed Issues?            |  No
Add config handling for authorize_url_parameters in OAuth 1 providers
Allows usage for things like Twitter force_login
> Forces the user to enter their credentials to ensure the correct users account is authorized.
https://developer.twitter.com/en/docs/basics/authentication/api-reference/authenticate.html
=> Add 'authorize_url_parameters' config support to OAuth 1 providers

src/Provider/Facebook.php
Now, Facebook API returns `tasks` instead of `perms` for each page.
=> [Facebook] Fix filtering of writable pages

hybridauth/Hybrid/Providers/Facebook.php
Now, Facebook API returns `tasks` instead of `perms` for each page.
=> V2 [Facebook] Fix filtering of writable pages

src/Provider/Twitter.php
| Fixed Issues?            | Fixes #1089 
| Patch: Bug Fix?          | Bug Fix for Twitter
The Twitter provider had the followers count and friends count reversed. "followers_count" from Twitter corresponds to "followed_by" and "friends_count" corresponds to "follows".
=> Fix Twitter follower and following counts

src/Provider/Vkontakte.php
**Updated API version to latest, getUserProfile.**
**Removed unnecessary unused fields and required fields, getUserProfile.**
**Added check for "photoUrl" using the has_photo field, getUserProfile.**
**Added support "photo_size" parameter for provider config.**
See examples for other providers: 
- [Foursquare.php#L85](https://github.com/hybridauth/hybridauth/blob/b515c3fae7669e9774718129754f334ebf3009e8/src/Provider/Foursquare.php#L85)
- [Foursquare.php#L120](https://github.com/hybridauth/hybridauth/blob/b515c3fae7669e9774718129754f334ebf3009e8/src/Provider/Foursquare.php#L120)
- …
=> Vkontakte getUserProfile fields

hybridauth/Hybrid/Auth.php
This change set updates a few Types in PHP Doc Blocks to better reflect what's possible. I was recently running a fairly large project through [Phan static analysis](https://github.com/phan/phan) and a few issues came up in the Hybrid Auth class specifically around `__construct()` and `initialize()` specifying they _only_ accept arrays. In reality they both accept both arrays or a string.
Comments have been updated to reflect this. Additionally, optional parameters that default to `null` have had their Doc Blocks updated as well.
| Fixed Issues?            | None
| Patch: Bug Fix?          | Not really
=> Update PHP Doc Blocks in Auth.php

src/Provider/Facebook.php
This fixes issue #1110
| Fixed Issues?            | Fixes #1110
| Patch: Bug Fix?          | Bug Fix
Uses a simple test on the email field to know if the emailVerified should be true or not.
=> Facebook emailVerified should not test "verified"

src/Adapter/OAuth2.php
| Fixed Issues?            | Closes #1065
Support of POST HTTP method for OAuth2 authentification
=> Allow POST method in OAuth2 authentification

src/Adapter/AbstractAdapter.php, src/Adapter/AdapterInterface.php, src/Adapter/OAuth1.php, src/Adapter/OAuth2.php, src/HttpClient/Curl.php, src/HttpClient/Guzzle.php, src/HttpClient/HttpClientInterface.php
Update Http interfaces to support multipart requests to support file uploads through apiRequest
```
$facebookAdapter->apiRequest('https://graph-video.facebook.com/xyz/videos',
'POST',
[
'title'       => $videoTitle,
'description' => $videoDescription,
'source'      => new \CURLFile($videoPath),
],
[],
true
);
```
=> Add support for multipart requests for video upload support

src/Provider/Odnoklassniki.php
https://apiok.ru/en/ext/oauth/server
5. Using a refresh_token With a refresh_token you can obtain an access_token via the simplified procedure by sending one POST query to:
https://api.ok.ru/oauth/token.do?refresh_token={refresh_token}&client_id={client_id}&client_secret={client_secret}&grant_type={grant_type}
=> Odnoklassniki missed tokenRefreshParameters

src/Hybridauth.php
| Patch: Bug Fix?          | Fix for logger
Since Logger initialization evoke during AbstractAdapter __construct ,
we need transfer config['debug_mode'] and config['debug_file'] to the provider, thereby transfer them AbstractAdapter __construct
=> Fix for Logger

src/Thirdparty/OAuth/OAuthSignatureMethod.php
Re: #1127
| Fixed Issues?            | Fixes #1127 
| Patch: Bug Fix?          | PHP 7.4 Enhancement
| Major: Breaking Change?  | N/A
| Minor: New Feature?      | N/A
Curly brace syntax to access arrays will be going away. Changed to 'standard' [ ] syntax.
=> Corrected array syntax for PHP 7.4 compatibility

src/Adapter/AbstractAdapter.php
In case we send $config['tokens']['access_token'] to Facebook provider, 
./Adapter/OAuth2.php will try to save it into storage (line 251), which is not configure yet. 
```
if ($this->config->exists('tokens')) {
$this->setAccessToken($this->config->get('tokens'));
}
public function setAccessToken($tokens = [])
{
$this->clearStoredData();
foreach ($tokens as $token => $value) {
$this->storeData($token, $value);
}
// Re-initialize token parameters.
$this->initialize();
}
```
=> configure() should be after setStorage()

src/Data/Collection.php, src/Provider/Slack.php, src/Provider/TwitchTV.php
| Minor: New Feature?      | Adds a provider for logging in with Slack
Adds a new provider for logging in with https://slack.com/.
In order to use it, a [Slack app](https://api.slack.com/docs/sign-in-with-slack) with the permission scopes `identity.basic`, `identity.email` and `identity.avatar` needs to be created. It is not necessary to add the app to a workspace (in fact it is not even possible if the app has only the `identity.*` scopes).
=> Add Slack provider

src/Adapter/OAuth1.php
I had an issue where the AWeber adapter I built was throwing a 401 error because the oauth parameters like oauth_signature were being added to the request body.
Removing that line fixed the issue.
=> Remove oauth1 authorization parameters from request body

src/Provider/Twitter.php
| Fixed Issues?            | #1167
Fixes the error code":32,"message":"Could not authenticate you." by sending the include_email parameter in an array instead of directly in the query string.
=> Fix error : code":32,"message":"Could not authenticate you."

src/Provider/TwitchTV.php
**Problem:**
Apparently Twitch now needs the request header `Client-ID` additionally to `Authorization`.
If it's missing, `TwitchTV::apiRequest()` returns the following response:
`{"error":"Unauthorized","status":401,"message":"Client ID and OAuth token do not match"}.`
Here is the official statement on Twitch's developer pages regarding the change, which became active on May 1st: https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916
Solution:
Just add `$this->clientId` to the appropriate request header.
Issue: https://github.com/hybridauth/hybridauth/issues/1170
=> Fix "Client ID and OAuth token do not match" with provider TwitchTV

src/Provider/Twitter.php
This just adds comments to the Twitter provider's code to clarify why it is OAuth1 and what 'authorize' is for.
It wasn't obvious without reading Twitter's API documentation.
=> Improved code comments documenting Twitter provider

src/Provider/Dropbox.php
Brings back Dropbox, which was in Hybridauth v2 as an additional provider, but not Hybridauth v3 yet. Upgrades to the Dropbox v2 API this time.
=> Reimplemented Dropbox for Hybridauth v3, using Dropbox v2 API this time

src/Provider/BitBucket.php
This makes 3 improvements to the BitBucket provider...
1) Provides a URL to do the config (which is not so obvious)
2) Support profile URLs
3) Fix a typo in a code comment
=> BitBucket: Link to OAuth2 config URL, support profile URL, fix typo

src/Provider/Vkontakte.php
Vkontakte uses non-standard terminology for the OAuth settings - so comment the mappings in the provider code file.
=> Document where the config settings on Vkontakte come from

src/Adapter/OAuth2.php
| Patch: Bug Fix?          | Arguable
| Major: Breaking Change?  | Debatable
We need to put clear focus on an OAuth flow where the user explicitly denies the login. i.e. they click something like a Cancel or a No button. Currently OAuth1 handles this, but OAuth2 just rolls it into a generic error. Use AuthorizationDeniedException for OAuth2.
=> AuthorizationDeniedException should be used for OAuth2

src/Provider/Authentiq.php, src/Provider/Yahoo.php
A couple of providers throw UnexpectedValueException instead of UnexpectedApiResponseException. Fixing this should not create a compat issue because UnexpectedApiResponseException is a subclass of UnexpectedValueException.
=> Fix incorrect exceptions being thrown by a couple of providers

src/Adapter/OAuth1.php, src/Adapter/OAuth2.php
| Major: Breaking Change?  | Probably not
Exception messages are not correct. Mainly it complains about "invalid <some kind of token>" for situations where there is actually no token passed. Change these to accurate messages.
In one case (the second line change of OAuth1.php it says access_token when it should say oauth_token. This is assuming the initial token is consistently called the oauth_token and exchanged for an access_token. It also makes it consistent with the specific exception used.
=> Fix various bad error messages and inconsistencies in exceptions

src/Provider/StackExchange.php
This fixes a couple of things I found testing the StackExchange provider...
First, it needs clearly documenting the 'site' parameter is needed.
Second, weirdly you need to explicitly pass the token to get the profile, even though the Bearer token header is passed.
=> StackExchange fix and clarification

src/Provider/Facebook.php
| Fixed Issues?            | Fixes #1097 
To get consistent gender options in English you need to tell the API your locale (as per https://stackoverflow.com/questions/35118373/facebook-graph-api-gender).
I couldn't test this as user_gender permission needs app approval, which I don't have.
But I think it'll work and it doesn't break anything.
=> Pass locale to Facebook API

src/Adapter/AbstractAdapter.php, src/Adapter/OAuth1.php, src/Adapter/OAuth2.php, src/Provider/Apple.php, src/Provider/Authentiq.php, src/Provider/DeviantArt.php, src/Provider/Discord.php, src/Provider/Google.php, src/Provider/Odnoklassniki.php, src/Provider/Patreon.php, src/Provider/QQ.php, src/Provider/Telegram.php, src/Provider/Vkontakte.php
| Fixed Issues?            | Fixes #1218 
| Patch: Bug Fix?          | Arguably yes
| Minor: New Feature?      | Debatable
The refresh token handling code in Hybridauth has some issues, which this patch fixes.
1) At a basic level, OAuth2 is assuming every OAuth implementation supports refresh tokens, and it tries refreshing expired tokens even when it has no refresh token.
2) Some providers then override this with null-op functionality, which is inconsistent. For example, Google provider didn't override it but my testing shows it does not have refresh tokens.
3) isConnected is implemented in AbstractAdapter with hard-baked assumption that then has to be overridden away for OpenID. Messy.
4) For …
=> Refactor refresh token handling to fix some messy code and bugs

src/Provider/Telegram.php
Domains may have CSP enabled, in which case script tags need a nonce. Allow this via configuration.
=> Need to support nonces for domains that have CSP enabled

src/Provider/Facebook.php
Correct Facebook API (v.8.0, current API)
- Introducing API Graph v8.0: https://developers.facebook.com/blog/post/2020/08/04/Introducing-graph-v8-marketing-api-v8/
=> Correct Facebook API (v.8.0, current API)

src/Thirdparty/OpenID/LightOpenID.php
There's a PHP8 compat issue in `src/Thirdparty/OpenID/LightOpenID.php`.
=> Fix (only) error coming up in PHP8 linting, with 3rd party OpenID lib

composer.json
Sometimes dependencies will cause conflicts. In my case it was `phpseclib`. I not use apple provider so I do not need those deps.
And even if I used it - phpseclib already exist and loaded in my case.
More detail about problem here https://github.com/zorn-v/nextcloud-social-login/issues/218
=> Move apple related deps to suggest section

src/Provider/Keycloak.php
Minor: Add Keycloak Provider.
Add Keycloak Provider provider based on OAuth2 class.
Example config:
'Keycloak' => [
'enabled' => true,
'url' => 'https://your-keycloak', // depending on your setup you might need to add '/auth'
'realm' => 'your-realm',
'keys' => [
'id' => 'client-id',
'secret' => 'client-secret'
]
]
=> Add Keycloak Provider

src/HttpClient/Guzzle.php
| Minor: New Feature?      | x
Hi there, I'm making this pull request because one of my providers are using a PATCH method request and the body params must be a json payload instead of an array. I saw that the Curl file already has the PATCH implementation but not on Guzzle.
Cheers!
=> Add PATCH request method to Guzzle to accept body json payload

src/Data/Parser.php
| Fixed Issues?            | Fixes #1318
Fixes `E_DEPRECATED: date_parse(): Passing null to parameter #1 ($datetime) of type string is deprecated`
=> Do not pass null to date_parse

src/Data/Parser.php, src/Provider/Facebook.php, src/Provider/Spotify.php
| Fixed Issues?            | none
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | TBD
| Minor: New Feature?      | no
This is a proposal for a code cleanup. Since Parser is an internal class it should not be considered a breaking change. Feel free to discard it if it is a breaking change
=> Remove unused $separator in parseBirthday

src/Provider/Apple.php
| Fixed Issues?            | Fixes #1331
fIrebase/jwt 6.2.0 has changed the way `jwt::decode()` is called. Because this is just a suggested package in hybridauth, the version can not be restricted in composer.json. Instead this patch adds an implementation to call `jwt::decode()` required by fIrebase/jwt 6.2.0 and later and does a version check to decide which call to use.
The patch has been tested with firebase/php-jwt version 5.5.1 and with version v6.2.0 successfully.
=> Provide support for Firebase/JWT version 6.2

src/Adapter/OpenID.php
| Fixed Issues?            |  
Fixes the following deprecation message by type casting a function parameter.
```console
Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/hybridauth/hybridauth/src/Adapter/OpenID.php on line 255
```
=> Fix PHP 8.1 deprecation in OpenID.php

src/Provider/Apple.php
| Fixed Issues?            | Fixes #1340
Check if Composer\InstalledVersions is available (not available with composer version 1.x) before checking the installed JWT version. If no version check is available, it is assumed an old JWT version (< 6.2) is installed.
(additionally JWT versions are now compared more safely using version_compare(), and I did some minor code cleanup and phpDoc updates)
=> Apple JWT version check fixed for composer 1

src/Provider/LinkedIn.php
Both parameters are needed to be able to refresh the access token using the refresh token for LinkedIn.
=> Added client id and secret to refresh parameters

src/Provider/Apple.php
solves an undefined property on null error if scope is kept with "email" instead of "name email".
solves an undefined property on null error if scope is keeped with "email" instead of "name email".
=> Bugfix scope "email" Update Apple.php

src/Adapter/OAuth2.php
| Fixed Issues?            | https://github.com/hybridauth/hybridauth/issues/1301, partially
There are some rare interactions where the cached OAuth2 state can get used without the login flow succeeding, like if a timeout happens or the user hits back at just the wrong moment, or other cases which I do not understand. If this happens, the browser gets jammed and cannot login, because it's stuck with an old session cookie with the invalid state.
Erase that invalid state when it is discovered.
This is part of addressing https://github.com/hybridauth/hybridauth/issues/1301. This isn't a full fix because while this defends against the …
=> Clear invalid authorization_state during OAuth2 login

src/Provider/LinkedInOpenID.php
| Fixed Issues?            | [Fixes #1](https://github.com/hybridauth/hybridauth/issues/1385)
| Major: Breaking Change?  | Yes
Current LinkedIn OAuth method is [deprecated](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin) since August 1, 2023. 
We should migrate to OpenID.
If you create a new LinkedIn app, `r_liteprofile` and `r_emailaddress` scopes no longer exist. `r_liteprofile` and `r_emailaddress` still works for old App prior to August 1, 2023.
New scopes are : `openid`, `profile` & `email`
=> Initial LinkedIn OpenID support

src/Provider/Keycloak.php, tests/Provider/KeycloakTest.php
| Minor: New Feature?      | Support Keycloak organization claim
Keycloak now supports "[organizations](https://www.keycloak.org/2024/06/announcement-keycloak-organizations)". 
As a result, the token issued by keycloak may contain a claim as follows:
```json
"given_name" : "Alice",
"family_name" : "Jenkins",
"organization": {
"orga": {}
}
```
The `organization` claim is useful in a multitenant context as it can be used by clients (e.g.: from ID Tokens) and resource servers (e.g.: from access tokens) to authorize access to protected resources based on the organization that a user belongs to.
This change is adding (when present) the …
=> Add support for keycloak organization claim

src/Provider/GitHub.php, src/Provider/Google.php, src/Provider/MicrosoftGraph.php
| Patch: Bug Fix?          | Yes (Google/Github/MSGraph providers)
| Major: Breaking Change? | No
**Description**:
After successful authentication, access token is properly returned by below Identity Providers: Google/Github/MSGraph. But without the refresh_token needed in case of expiration. then it is not possible to renew the access token later on. 
Current PR aims at enhancing HTTP parameters sent and received to make Google/Github/MSGraph work from authentication to access token renewal.
=> Refresh token fixes

src/Provider/QQ.php
| Fixed Issues?            | NO
| Patch: Bug Fix?          |  Fix QQ can't parse to get openid
According to QQ documentation: [获取用户openid_oauth2-0](https://wiki.connect.qq.com/%e8%8e%b7%e5%8f%96%e7%94%a8%e6%88%b7openid_oauth2-0)
| Params                        | Require     |    Describe
| ------------- | ---------- | ----------
| access_token           | Y| 在Step1中获取到的access token。
| fmt          |  N | 因历史原因，默认是jsonpb格式，如果填写json，则返回json格式
Request interface: https://graph.qq.com/oauth2.0/me can provide a valid parameter `fmt` to specify the return format. Currently, the `json` return format is supported, and the original processing method has been unable to …
=> Fix QQ can't parse to get openid

src/Hybridauth.php
| Fixed Issues?            |  No
The provider name passed to getAdapter through the authenticate function is not converted to lowercase, so in the case when the class_exists does not autoload the class, and when the comparison is made with the file name let's say GitHub.php then the condition fails to match with the Provider name(which has not been lowercased) which returns an error "Unknown Provider".
=> Unknow provider error

src/Adapter/AbstractAdapter.php, src/Adapter/AdapterInterface.php, src/Hybridauth.php, src/Provider/Instagram.php
In PHP 8.4, with exceptions being converted through a set_error_handler() method, we get errors like this:
```
Hybridauth\Adapter\AbstractAdapter::__construct(): Implicitly marking parameter $httpClient as nullable is deprecated, the explicit nullable type must be used instead in /var/www/apps/mycompiler/8528a9f9/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php:93
```
Since such a design is in use by many PHP frameworks and codebases, I'd like to change the occurrences of nullable variables to use `?type x = null` instead of `type x = null`.
Thank you.
=> Fix issues with PHP 8.4 and changes to nullable vars

src/Adapter/AbstractAdapter.php, src/Adapter/FilterService.php, src/Adapter/OAuth1.php, src/Adapter/OAuth2.php, src/Hybridauth.php, src/Provider/Keycloak.php, src/Provider/Telegram.php, src/Storage/StorageImpl.php, tests/Provider/KeycloakTest.php
| Patch: Bug Fix?          | Yes (Keycloak)
| Major: Breaking Change? | No
**Description**:
Authenticate is working properly with Keycloak provider. We receive the tokens from IdP (access_token/refresh_token). This PR provides a fix to make oAuth2 refresh token mechanism work by providing client_id/client_secret .
We also added StorageImpl class to ease writing tests (avoid Session instanciation and session_start()).
=> Make Keycloak refresh token work
