hybridauth/hybridauth

additional-providers/hybridauth-dribbble/Providers/Dribbble.php
additional-providers/hybridauth-wordpress/Providers/WordPress.php

This is a preliminary (and the simplest) integration with WordPress and Dribbble, however they both work fine in my tests. There is still something to do (eg.: posting on blog / dribbble), but I'd say they are stable enough to be added to hybridauth.

Created WordPress and Dribbble provider

---

hybridauth/Hybrid/Endpoint.php

It was very rude, especially for just library, now should be better

Do not replace $_REQUEST with something else

---

userguide.html
userguide/IDProvider_info_Dribbble.html
userguide/IDProvider_info_Github.html

Hi,
in these 3 commits I've added Dribbble in the documentation and updated GitHub's one. WordPress will follow, but next week.

Added Dribbble documentation, updated GitHub's one

---

userguide/IDProvider_info_Dribbble.html

Sorry, I forgot to update some things in the new documentation.
Anyway, I would like to ask you a question: how is Hybridauth 3.x development going? I haven't seen recent commits and that's a shame because it looks A LOT more professional and neat than the current version.

Updated Dribbble docs (Disqus ID missing)

---

src/Provider/Google.php

This is the valid pull request, my bad for this [#414](https://github.com/hybridauth/hybridauth/pull/414)

Changing structure for get the email from Google provider

---

.gitignore
examples/signin_signup/application/models/authentication.php
examples/signin_signup/application/public/css.css
examples/signin_signup/application/views/users/complete_registration.html
examples/signin_signup/application/views/users/login.html
examples/signin_signup/application/views/users/register.html
examples/signin_signup/database.sql
hybridauth/index.php

Tiny look and feel changes
Set facebook on top
Used default values in the database/sql

Tiny look and feel changes

---

hybridauth/Hybrid/Providers/Google.php

https://github.com/hybridauth/hybridauth/issues/386#issuecomment-87992716

fix access to access_token

---

additional-providers/hybridauth-github/Providers/GitHub.php

property_exists() expects the first parameter to be the class, the second a string to test.

Parameter order incorrect

---

additional-providers/hybridauth-sina/thirdparty/Sina/saetv2.ex.class.php
hybridauth/Hybrid/Endpoint.php
hybridauth/Hybrid/Providers/LinkedIn.php
hybridauth/Hybrid/thirdparty/OAuth/OAuth.php

This fixes an issue with redeclaring classes when using composer.
Should fix issue #428.

Disable autoloading for class_exists() checks

---

hybridauth/Hybrid/Auth.php

Parentheses are definitely needed here

Fix for confusing conditional expression, not even sure it worked fine

---

src/Adapter/OAuth2.php
src/Provider/Odnoklassniki.php
src/Provider/README.md
src/Provider/Vkontakte.php

Added Odnoklassniki Provider.
Also fixed Vkontakte provider. There users.getInfo method was changed to users.get.
Now you can get email from Vkontakte with auth token.

Odnoklassniki Provider

---

additional-providers/hybridauth-slack/Providers/Slack.php
hybridauth/Hybrid/thirdparty/LinkedIn/LinkedIn.php

Slack OAuth2 provider

---

additional-providers/hybridauth-steam/Providers/Steam.php

Steam provider xml parsing error

---

additional-providers/hybridauth-xuite/Providers/Xuite.php

Xuite platform (http://xuite.net) provides  CHT member (https://member.cht.com.tw/) Oauth service. more info please refer to: http://api.xuite.net/

 add xuite's oauth provider

---

.travis.yml
src/Adapter/AbstractAdapter.php
src/Adapter/OAuth1.php
src/Adapter/OAuth2.php
src/Exception/NotImplementedException.php
src/HttpClient/Util.php
src/Hybridauth.php
src/Provider/Dribbble.php
src/Provider/Facebook.php
src/Provider/GitHub.php
src/Provider/Google.php
src/Provider/Instagram.php
src/Provider/LinkedIn.php
src/Provider/Mailru.php
src/Provider/Odnoklassniki.php
src/Provider/Steam.php
src/Provider/Tumblr.php
src/Provider/TwitchTV.php
src/Provider/Twitter.php
src/Provider/Vkontakte.php
src/Provider/WindowsLive.php
src/Provider/WordPress.php
src/Thirdparty/OpenID/LightOpenID.php

Some PSR2 love. Added couple of travis builds too.

3.0.0 remake

---

src/HttpClient/Util.php

Added possibility to set custom callback instead of `exit()` during redirect

---

src/Hybridauth.php
src/Logger/Logger.php

For https://github.com/hybridauth/hybridauth/commit/5eb87ef88133e16fa2420b9515734ef12aed04b2#commitcomment-11642902

Small fix for inability to pass string debug mode introduced few commits ago

---

src/Hybridauth.php

Avoid isset checks.

---

hybridauth/Hybrid/Providers/Facebook.php

Switches from hometown to location

---

hybridauth/Hybrid/thirdparty/Facebook/base_facebook.php

Facebook bug when checking against tokens twice in the same handler
http://stackoverflow.com/questions/7340764/problem-with-facebook-login-not-matching-csrf-state-token/20313737#20313737

Facebook bug fixed

---

hybridauth/Hybrid/Endpoint.php

Minor change of text log in Endpoint.php on line 181.
Thank you.

Fix text log in Endpoint.php

---

additional-providers/hybridauth-draugiem/Providers/Draugiem.php

Fixed an error caused by API not always returning the birthday of the user.

[Draugiem] API does not always return the birthday object

---

hybridauth/Hybrid/Providers/Twitter.php
hybridauth/config.php

Add email option to Twitter API as detailed here https://dev.twitter.com/rest/reference/get/account/verify_credentials

[Twitter] Add email option to Twitter API

---

additional-providers/hybridauth-draugiem/Providers/Draugiem.php

Birthday variable doesn't seem to be consistent.
Referenced by @cherijs in [here]( https://github.com/hybridauth/hybridauth/commit/0601cdc0fa0d5ebbb79d18d581a8f29767bca52e#commitcomment-12994999).

Fixed a weird Draugiem API bug

---

additional-providers/hybridauth-xing/Providers/XING.php
additional-providers/hybridauth-xing/Providers/XINGJob.php
additional-providers/hybridauth-xing/Providers/XINGJobLocation.php
additional-providers/hybridauth-xing/Providers/XINGUser.php
additional-providers/hybridauth-xing/Providers/XINGUserPictureSize.php

This updates the XING Provider to v1.1.0.

Updated XING Provider to v1.1.0

---

additional-providers/hybridauth-odnoklassniki/Providers/Odnoklassniki.php

* Switch ``photoURL`` to ``photoBIG`` in ``getUserProfile()`` function.
* Small refactoring code.

[Odnoklassniki] Get better size of user avatar

---

additional-providers/hybridauth-steam/Providers/Steam.php

Need string conversion for $data->customURL and check it is not empty

Fix Steam profileUrl

---

additional-providers/hybridauth-odnoklassniki/Providers/Odnoklassniki.php

* Add ``$fields`` variable;
* Change ``pic_1`` to ``pic190x190``;
* Change ``pic_2`` to ``pic640x480``;
* Refactoring.

[Odnoklassniki] Refactoring and add $fields variable

---

additional-providers/StackExchange

This is a basic integration for StackExchange network using HybridAuth, as requested in #590. Change "stackoverflow" with other sites in their network to login with them. This is needed because their OAuth implementation requires a specific site.
Feel free to merge & add extra features.

Created a basic StackExchange integration

---

additional-providers/hybridauth-humanitarianid/Providers/HumanitarianId.php
additional-providers/hybridauth-humanitarianid/thirdparty/HumanitarianId/HumanitarianIdOAuth2Client.php

This code provides a provider for the Humanitarian ID authentication service with hybridauth. More information about Humanitarian ID is available here: http://about.humanitarian.id

Hybridauth humanitarianid

---

additional-providers/hybridauth-vkontakte/Providers/Vkontakte.php

Vkontakte changed URLs in documentation https://new.vk.com/dev/auth_sites
There is small code style fixes also.

[Vkontakte] Update URLs and small fixes with reformat

---

additional-providers/hybridauth-weibo/Providers/Weibo.php

Weibo provider is a simple version of Sina provider which use the standard OAuth2Client and just used for login and get user information. There is not other dependency needed, just copy into one's Providers directory and it works. So I think it is very useful for someone who only want to connect user in weibo but do not need other features.

Add Weibo Provider.

---

hybridauth/Hybrid/Providers/Google.php

As seen in real world apps, it's possible not to receive $min, so Hybridauth throws an Exception.
Didn't find much info about it, but this page explaining the Java class for Android gives clues about the issue
https://developers.google.com/android/reference/com/google/android/gms/plus/model/people/Person.AgeRange#public-methods
So, we cannot take for granted we'll receive $min.
Here you can see the typical Exception you may get
```
[2016-04-04 21:36:48] production.ERROR: exception 'ErrorException' with message 'Undefined property: stdClass::$min' in /var/www/lektu/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Providers/Google.php:166
Stack trace:
#0 /var/www/lektu/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Providers/Google.php(166): Illuminate\Exception\Handler->handleError(8, …
```

Google plus api correct age values

---

additional-providers/hybridauth-pinterest/Providers/Pinterest.php

I had to implement this on a recent project.
Hope this helps ;)

Adding Pinterest provider

---

hybridauth/Hybrid/Provider_Adapter.php

There is a redirect mode, but is never used as far i can see.
In some cases a JS redirect can be usefull. 
$hybridauth->authenticate('Twitter',array('redirect_mode'=>'JS'));

Make use of the redirect mode

---

hybridauth/Hybrid/Providers/LinkedIn.php

Added ability to set LinkedIn's fields: now you can for example require photo in original (larger) version by setting:
```
LinkedIn:
enabled: true
keys:
key: '***************'
secret: '*********************'
fields:    # this section is optional
- id
- first-name
- last-name
- public-profile-url
- 'picture-urls::(original)'    # this line is important
- email-address
- date-of-birth
- phone-numbers
- summary
```

Added ability to set LinkedIn's fields

---

additional-providers/hybridauth-amazon/Providers/Amazon.php
additional-providers/hybridauth-amazon/thirdparty/Amazon/AmazonOauth2Client.php

This PR adds Amazon Provider and custom OAuth2Client. See also #238

Add Amazon Provider

---

additional-providers/hybridauth-strava/Providers/strava.php

Strava is the social network for athletes. A global community of millions of runners, cyclists and triathletes, united by the camaraderie of sport.

Add strava as new provider

---

additional-providers/hybridauth-pinterest/Providers/Pinterest.php

- OAuth with access token, exclude step with getting code
- Finish authorize with saving access token
- Added Pinterest API methods
- Boards : Create | Fetch | Delete
- Pins: Create

[Pinterest] Additional provider updates

---

userguide/tuts/change-hybridauth-endpoint-url.html

Add custom endpoint documentation

---

CHANGELOG
additional-providers/hybridauth-github/Providers/GitHub.php

I tried to follow the existing coding style. Fixes #702.

Update GitHub provider to recognize verified email

---

additional-providers/hybridauth-tumblr/Providers/Tumblr.php

I changed the function setUserStatus in provider Tumblr. Now you can post not just a string with the text type, but other types of blog posts (see https://www.tumblr.com/docs/en/api/v2#posting).

Modifying of Tumblr function for posting.

---

hybridauth/Hybrid/Provider_Adapter.php

[Core] Patch for passing more arguments in called method

---

hybridauth/Hybrid/Providers/Live.php

* [Live] Sets redirect_uri to redirect_uri from config array to fix problems with windows live oauth query param restriction

* [Live] Fix authorize_url for windows live

---

userguide.html
userguide/IDProvider_info_Stripe.html

Related to this pull request - https://github.com/hybridauth/hybridauth/pull/711

[Stripe] Add documentation

---

additional-providers/hybridauth-discord/Providers/Discord.php

[Discord] Add new provider.

---

hybridauth/Hybrid/Providers/Google.php

Resolved issue with google provider in obtaining contacts.

[Google] Resolved issue with google provider in obtaining contacts

---

additional-providers/hybridauth-envato/Providers/Envato.php

Add Envato as the additional provider. 
here is the API documentation: https://build.envato.com/api/#market_Username

add envato oauth

---

examples/example_01.php

Just cleaning up the documentation.

Typos in example comments

---

hybridauth/Hybrid/Providers/Facebook.php

Fix issue with cannot use object of type Facebook\FacebookResponse as array

---

userguide/IDProvider_info_Facebook.html

[Facebook] Add Installation guide

---

hybridauth/Hybrid/Auth.php
hybridauth/Hybrid/Providers/Facebook.php

Fix issue with including autload.php in v2.9.2

Improve logic for including autoload.php

---

userguide/IDProvider_info_Facebook.html

Add minimal requirements for Facebook provider.

[Facebook] Add Requirements

---

hybridauth/Hybrid/Providers/Yahoo.php
hybridauth/config.php

1. Fix issues related to Yahoo provider: #787 
2. Use the latest API version (Yahoo OAuth 2.0)
I have upgraded Yahoo provider based on https://developer.yahoo.com/oauth2/guide. Will also update [yahoo documentation](https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Yahoo.html) because it's not actual.

[Yahoo] Upgrade to OAuth 2.0

---

userguide/IDProvider_info_Yahoo.html

Use actual version of Yahoo documentation.

[Yahoo] Update documentation

---

.gitignore
additional-providers/hybridauth-draugiem/thirdparty/Draugiem/DraugiemApi.php

* Addition
from https://getcomposer.org:
> You should commit the composer.lock file to your project repo so that all people working on the project are locked to the same versions of dependencies
and I agree, but we can ignore this for HA library. 
We use `"facebook/graph-sdk": "^5.4"` as composer dependency. So, it will always allow non-breaking updates which good for us. 
p.s. this PR is also fixed some coding standards to prevent failed build in Travis CI.

Add composer.lock to gitignore

---

userguide/IDProvider_info_LinkedIn.html

* Addition
Documentation fixes for PR #803

[LinkedIn] Update documentation for OAuth 2.0

---

userguide/IDProvider_info_Vimeo.html

* Addition
Documentation fixes for PR #807

[Vimeo] Update documentation for OAuth 2.0

---

src/HttpClient/Curl.php

Added JSON payload support to POST and newly introduced PUT HTTP verb
cc @miled

JSON Payload Support & New PUT verb to cURL Client

---

src/HttpClient/Guzzle.php

Added JSON payload support to POST and newly introduced PUT HTTP verb
cc @miled

JSON Payload Support & New PUT verb to Guzzle Client

---

src/Adapter/AbstractAdapter.php

Some service return 201 to 299 when a POST, PUT OR PATCH request is successful. Eg Aweber which am presently building for.

Not only 200 is a successful status code

---

src/Adapter/DataStoreTrait.php

PHPDoc fixes

---

hybridauth/Hybrid/Providers/Live.php

Fix some issues for a Live provider. Now works with the latest api.

[Live] Fix authorize_url

---

hybridauth/Hybrid/Providers/Facebook.php

Resolves #844 
btw, documentation will be added in the next PR.

#844: Add photo_size for fb

---

docs/developer-ref-user-contacts.md

(select one:)
* Breaking change
* Addition
* Patch for #
* New provider
What do you want to achieve with this PR?
Your description...

Type Error

---

userguide/IDProvider_info_OpenStreetMap.html

This is documentation for new Provider given on PR #869

Add documentation for provider OpenStreetMap

---

userguide/IDProvider_info_PayPal.html

[PayPal] Documentation

---

src/Adapter/OAuth1.php

Refresh consumer token for OAuth1 when setAccessToken is called

---

docs/developer-ref-user-status.md
docs/providers.md
src/Provider/LinkedIn.php

#884: Adds setUserStatus for LinkedIn

---

src/Provider/Twitter.php

#885: Fixes setUserStatus for twitter

---

src/Provider/Twitter.php

[Twitter] Remove deprecation endpoint

---

src/HttpClient/Curl.php
src/HttpClient/Guzzle.php

Fixed merging client headers

---

docs/providers.md
src/Provider/WeChat.php
src/Provider/WeChatChina.php

* New provider
Spotify was taken.
Can't test without registered and approved account, but should work.

added WeChat, fixes #471.

---

src/User/Profile.php

This will allow to set extra fields in the user profile.

Add extra $data  to Profile class

---

src/Provider/Instagram.php
src/Provider/LinkedIn.php
src/Provider/Twitter.php

Resolves #512 and improves #851

Add followers counts for Twitter, Instagram and LinkedIn

---

docs/introduction.md

Fixed typo in documentation example.

Fixed typo in documentation example.

---

src/Adapter/AbstractAdapter.php
src/Adapter/OAuth1.php
src/Provider/Odnoklassniki.php

Re-init tokens when setAccessToken is called

---

src/Adapter/AbstractAdapter.php

Improve providerId setter

---

src/Provider/Facebook.php
src/Provider/Instagram.php

Fix instagram provider

---

src/Provider/Vkontakte.php

* Addition
Correct api request to VK.com
Required api version number in requests

Required api version number in requests Vkontakte provider

---

additional-providers/hybridauth-vkontakte/Providers/Vkontakte.php

see https://github.com/hybridauth/hybridauth/pull/924

Required api version number in requests Vkontakte provider (v2)

---

additional-providers/hybridauth-vkontakte/Providers/Vkontakte.php

Improved Exception message for API requests getUserProfile in Vkontakte provider

Improved Exception msg for Vkontakte provider (v2)

---

src/Adapter/OAuth2.php

Allow to use custom authorization_state

---

src/Provider/Vkontakte.php

* Patch for #771 
- Updated provider according [documentation](https://vk.com/dev/manuals).
- Tested manually on pure hybridauth:
- Documentation will be updated later if PR will be merged.

#771: Updated Vkontakte provider.

---

src/Adapter/OpenID.php

Wargaming OpenID do post request for example

Make possible OpenID auth via POST

---

src/Provider/Discord.php

[Discord] Makes display name more unique.

---

docs/providers.md
src/Provider/MicrosoftGraph.php

(select one:)
* New provider
The windows live api is deprecated. I have created another provider to use the new MicrosoftGraph endpoints. 
What do you want to achieve with this PR?
Your description...

Add Provider for MicrosoftGraph

---

src/Provider/Dribbble.php

| Fixed Issues?            | Fixes #962

Upgrade Dribbble API to v2

---

hybridauth/Hybrid/Providers/Facebook.php
hybridauth/Hybrid/Providers/LinkedIn.php
hybridauth/Hybrid/Providers/Paypal.php
hybridauth/Hybrid/Providers/Yahoo.php

| Fixed Issues?            | Yes, returned back support for PHP 5.2
| Documentation PR         | Replaced [] to array()
Changes in 4 files in Providers/ folder to make the code support PHP 5.2 again. Replaced [] construction to array() declaration.

Return back support for PHP 5.2

---

docs/providers.md

| Fixed Issues?            |
| Documentation PR         | Formatting and organization improvement.
[skip ci]
Providers are now in alphabetical order and the text inside of the columns is centered.

Sorted providers and improved formatting

---

hybridauth/Hybrid/Providers/LinkedIn.php

| Fixed Issues?            |  No
Added option to set status as company for LinkedIn provider for v2.

Added option to set status as company for LinkedIn.

---

src/Provider/LinkedIn.php

| Fixed Issues?            | Fixes #1020

Upgrade oauth endpoints for LinkedIn

---

hybridauth/Hybrid/Providers/Google.php

| Fixed Issues?            | Fixes #1024 for v2
| Major: Breaking Change?  | Not sure
| Minor: New Feature?      | Sort of
Backport changes from 6123c31 for v2. I think I removed the right things, and login is working for me, but we don't use the Contacts API so I'm not sure if everything is right there.

Remove Google Plus support in v2

---

src/Provider/Amazon.php

Support Login with Amazon (LWA)

Added Amazon provider

---

src/Provider/LinkedIn.php

| Fixed Issues?            | Fixes #1020
| Major: Breaking Change?  | [x]
This PR provides changes for API v2 of LinkedIn provider.
Migration guide: https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq
It's not backward compatible. All users should be upgraded to use it.
A big thanks to @RazaGR for providing initial version.

[LinkedIn] Upgrade API to v2

---

src/HttpClient/Curl.php
src/HttpClient/Guzzle.php

Add DELETE request method support

---

docs/providers.md
src/Provider/Paypal.php

| Minor: New Feature?      | Paypal
| Documentation PR         | https://developer.paypal.com/docs/api/identity/v1/

Paypal OAuth2

---

src/Provider/LinkedIn.php

| Fixed Issues?            | Fixes #1063

[LinkedIn] Get first name and last name on preferred locale

---

hybridauth/Hybrid/Providers/LinkedIn.php
hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php

| Fixed Issues?            | Fixes #1067 
| Major: Breaking Change?  | +
This PR provides changes for API v2 of LinkedIn provider.
Mostly it's back port of #1059.
Migration guide: https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq
It's not backward compatible. All users should be upgraded to use it.
Thanks to @janadam-hbf for working on initial version 🥇

[LinkedIn] Upgrade to API v2

---

README.md
hybridauth/Hybrid/Auth.php

Release 2.15.1

---

additional-providers/hybridauth-vkontakte/Providers/Vkontakte.php

| Fixed Issues?            | `Update getProfile function to work with 5.x Vkontakte API` 

Update provider to work with Vkontakte 5.x API

---

src/Provider/Telegram.php

| Fixed Issues?            | #1052 
| Patch: Bug Fix?          | `No`
| Major: Breaking Change?  | `No`
| Minor: New Feature?      | `Yes`
* Added Telegram provider.

added Telegram.

---

hybridauth/Hybrid/Provider_Adapter.php
hybridauth/Hybrid/Provider_Model.php
hybridauth/Hybrid/Provider_Model_OAuth2.php

Some porviders (e.g LinkedIn) do not provide refresh token in response. So, we need to handle it - just login once more.

[OAuth2] Re-login when access token is expired without refresh token

---

src/HttpClient/Curl.php

| Fixed Issues?            | None
| Minor: New Feature?      | Kinda?
Tested on Discord API method which didn't work out of box.
https://discordapp.com/developers/docs/resources/guild#modify-guild-member

Add support for PATCH requests in Curl client

---

hybridauth/Hybrid/Providers/Twitter.php

| Fixed Issues?            | Fixes #1004
- it uses HTTPS twitter image
- it makes photo size configurable

[Twitter] Make photo size configurable + https

---

docs/providers.md
src/Data/Parser.php
src/Provider/ORCID.php

| Fixed Issues?            | Fixes #1006
I created ORCID provider for auth and user profile. Because results from it's API are in XML, I also added XML parser to `Data\Parser`. Documentation of supported providers is also updated.

Add ORCID provider

---

src/HttpClient/Guzzle.php

| Fixed Issues?            | Fixed #1132

Add missing bracket

---

src/Provider/Vkontakte.php

| Minor: New Feature?      | New feature
Add getContacts method for Vkontakte provider

add getUserContacts method for Vkontakte provider

---

src/Provider/QQ.php

| Minor: New Feature?      | add China Tencent QQ OAuth2 provider
Adding new China Tencent QQ provider
Wiki(Chinese): https://wiki.open.qq.com

Add QQ provider

---

src/Provider/Discord.php

| Fixed Issues?            | Fixes #1142

Fix refreshAccessToken for Discord provider

---

src/Provider/Vkontakte.php

| Fixed Issues?            | Fixes #1148
| Patch: Bug Fix?          | -

[VK] Improve api request + add education field

---

src/Provider/Vkontakte.php

| Fixed Issues?            | Fixes #1148 

[VK] Add bdate field

---

additional-providers/hybridauth-instagram/Providers/Instagram.php

Similar to https://github.com/hybridauth/hybridauth/pull/1149 but for HA v2.

[v2] Upgrade Instagram API to Instagram Basic Display API

---

src/Provider/Odnoklassniki.php

| Fixed Issues?            |  
| Minor: New Feature?      | Add birthday field

[OK] Add birthday field

---

src/Provider/Patreon.php

Adding Patreon provider with basic login functionality (authorization + profile info).

add Patreon provider adapter

---

src/Provider/Patreon.php

| Patch: Bug Fix?          |Yes
| Major: Breaking Change?  |No
| Minor: New Feature?      |No
Hello, @ApacheEx 
you've closed the pr #1157 before I could check out the changes but there's a small error crept in attributes retrieval. This will make it all good again.
Thanks for quick responding.

Fix attributes getter in Patreon provider

---

src/Provider/Facebook.php

Fixes #1160 
Only tested to ensure I can still login on an existing application.

Upgrade facebook graph version to v6.0

---

src/Provider/Pinterest.php

| Patch: Bug Fix?          |No
| Major: Breaking Change?  |No
| Minor: New Feature?      |Pinterest provider
Include provider Pinterest OAuth2

Create Pinterest provider

---

src/User/Profile.php

| Fixed Issues?            | None
All of these properties can be null, as far as i can see.  Adding the correct type hints allows static analysis tools/IDEs  to understand this.

Make all types in Profile nullable

---

hybridauth/Hybrid/thirdparty/OAuth/OAuth.php

Update OAuth.php, PHP 7.4 compatibility

---

additional-providers/hybridauth-sina/thirdparty/Sina/saetv2.ex.class.php

Update saetv2.ex.class.php, PHP 7.4 compatibility

---

CONTRIBUTING.md
COPYING.md
examples/example_01.php
examples/example_07/callback.php
src/Exception/Exception.php
src/HttpClient/Curl.php
src/HttpClient/Guzzle.php
src/HttpClient/HttpClientInterface.php
src/Storage/Session.php
src/Storage/StorageInterface.php

Just making the project name consistent. I made the equivalent pull request to the docs too.

Write project name consistently

---

src/Provider/Reddit.php

This just adds photoURL, using the avatar set in Reddit.

Support photoURL as Reddit avatar

---

src/Provider/MicrosoftGraph.php

| Fixed Issues?            | Fixes #1025 
The MicrosoftGraph provider is rather lacking.
It couldn't get my consumer email.
It couldn't get a phone number if one is set.
And it makes a big assumption about tenant.
It also needs some docs work, as Microsoft make all this pretty confusing.
This pull request fixes all that.

Improve MicrosoftGraph provider

---

src/Provider/Telegram.php

This just provides a little guidance to help users get the Telegram provider working.

Some basic guidance on how to make Telegram provider work

---

src/Adapter/OAuth1.php
src/Adapter/OAuth2.php

I find it helpful to make it clear what URLs are failing when you get an endpoint error.

Show which URLs are failing when an endpoint returns an error

---

src/Provider/Facebook.php

| Fixed Issues?            | Fixes #1196 
| Patch: Bug Fix?          | Arguable
Implements support for Facebook token exchange, which is Facebook's alternative to refresh tokens.

Implemented Facebook token exchange mechanism

---

examples/example_07/callback.php
examples/example_07/index.php

| Fixed Issues?            | Fixes #1100, Fixes #1230

Fix example07 for closing popup via js

---

src/Provider/Telegram.php

| Fixed Issues?            | Fixes #1190
Implement profile URLs, for users who have set a username.

Support Telegram profile URLs

---

src/Adapter/OAuth1.php

| Fixed Issues?            | Fixes #1176
The currently begin/finish flow has incorrect assumptions. Code to precise situation of data flow and comment clearly.

Fix OAuth1 flow bug

---

src/Adapter/OAuth2.php
src/Provider/Vkontakte.php

Some code from https://github.com/hybridauth/hybridauth/pull/1217 went missing, presumably one of many recent merges, and also I missed a change for Vkontakte. Fix that.
I've reviewed against my fork and this is the only merge issue with all the various pull requests I've made.

Fix code went missing during merge / missed code from Vkontakte

---

src/Provider/WeChat.php

| Fixed Issues?            | Fixes #1191
I just implemented the suggestion changes, with cleanups.
I haven't actually tested. I think it is safe though, the changes make sense.

Fix WeChat, as per @champsupertramp suggestions

---

examples/example_02.php
examples/example_03.php
examples/example_04.php
examples/example_05.php
src/HttpClient/Guzzle.php
src/Provider/Apple.php
src/Provider/Facebook.php
src/Provider/Google.php
src/Provider/MicrosoftGraph.php
src/Provider/OpenID.php
src/Provider/StackExchange.php
src/Provider/Steam.php
src/Provider/Telegram.php
src/Provider/Twitter.php
src/Provider/Vkontakte.php

| Patch: Bug Fix?          | Kinda
I missed some issues inside code comments in my previous pull request.

Fix PSR-2 issues in comments

---

src/Provider/Medium.php

| Fixed Issues?            | Fixes #969 
| Minor: New Feature?      | Medium Provider
add new provider **Medium**
[Medium Developers](https://developers.medium.com/)
[Medium Applications](https://medium.com/me/applications)
[Medium Docs](https://github.com/Medium/medium-api-docs)

add provider Medium

---

src/Adapter/OpenID.php
src/Data/Parser.php
src/HttpClient/Curl.php
src/HttpClient/Guzzle.php
src/Provider/Apple.php
src/Provider/Authentiq.php
src/Provider/Facebook.php
src/Provider/MicrosoftGraph.php
src/Provider/Telegram.php
src/Provider/WeChat.php

| Fixed Issues?            |
I ran the code through a PHPStorm Inspect, as a part of another pull request I will soon make. I found some preexisting issues in the code.
Most of them are just very minor scanning issues relating to things like PHPdoc, that won't have any actual associated bugs. There are a few cases of PHP 5.4 not working though.
I just stuck to fixing what were obvious mistakes or needed fixing because they looked like nastier bugs to the scanner and we want to avoid unnecessary noise in there. I didn't try and fix anything in `Thirdparty` or do anything pedantic.

Various fixes from PHPStorm scan

---

src/Adapter/AbstractAdapter.php
src/Adapter/AdapterInterface.php
src/Adapter/OAuth1.php
src/Adapter/OAuth2.php
src/Provider/Facebook.php
src/Provider/Instagram.php

Implemented Token Exchange for Instagram, similar to Facebook but with a number of subtle differences.

Implemented Token Exchange for Instagram

---

.travis.yml
composer.json

| Fixed Issues?            | no
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | no
| Minor: New Feature?      | Run tests on supported PHP versions

Upgrade Travis configuration

---

src/Provider/Patreon.php

getContacts is not implemented for Patreon. Implement it as a way to get a list of patrons.
This is slightly fitting a round peg in a square hole, but I think it does make good sense to do it.

Patreon provider: Make getContacts return a list of patrons

---

src/Provider/Instagram.php

I previously implemented Instagram token exchange for the project. However, there's a flaw in my implementation which this pull request fixes.
Instagram and Facebook are subtly different, and both different from standard oAuth refresh token handling.
A long-lived Facebook token lasts forever.
A long-lived Instagram token lasts ~60 days, and needs refreshing - but it turns out the refresh mechanism is like token exchange but happens with some different parameters (and totally different from oAuth refresh tokens).
FB documentation isn't so great at describing these mechanisms.

Fix to Instagram Token exchange

---

hybridauth/Hybrid/Providers/Google.php

| Minor: New Feature?      | Improvement
With the option "prompt" now is possible to add in configuration "prompt = select_account" to force the user to select an account or enter the credentials.

Adding "prompt" as Google options

---

src/Provider/Apple.php

| Fixed Issues?            | Fixes #1292

Fix error handling for token signature

---

src/Provider/WeChat.php

| Fixed Issues?            | Fixes #1281

Fix issue with tokenRefreshParameters in WeChat

---

src/Provider/LinkedIn.php

| Fixed Issues?            | Fixes #1296
| Major: Breaking Change?  | possibly yes

Reduce scope of LinkedIn provider to be default: r_liteprofile r_emailaddress

---

additional-providers/hybridauth-humanitarianid/Providers/HumanitarianId.php

| Fixed Issues?            | Internal issues with a Provider
Hello, I am a maintainer for one of the services listed under `additional-providers` in the `v2` branch and we realized that the Provider class is a bit out of date. This PR brings it in line with the current service. 
As "proof" of authenticity, you can see my ongoing maintenance with on the official open-source repo for the service itself, Humanitarian ID: https://github.com/un-ocha/hid_api

Updates for HID Provider class

---

src/Provider/Amazon.php
src/Provider/Apple.php

| Fixed Issues?            |  no
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | no
| Minor: New Feature?      | yes
adds the refresh parameters for the Amazon, Apple providers

refresh params for the Apple, Amazon providers

---

src/Provider/Mastodon.php

Add Mastodon provider

---

src/Adapter/OAuth2.php

| Fixed Issues?            | Fixes #1380
| Patch: Bug Fix?          | Fixes a CSRF issue with state not being checked properly

Require a state to avoid CSRF, see issue #1380 for details

---

src/Thirdparty/OAuth/OAuthConsumer.php

Prevent error "Creation of dynamic property is deprecated."

Support php 8.2

---

src/Hybridauth.php

| Major: Breaking Change?  | Bo
| Minor: New Feature?      | Yes (to ease configuration)
Feature description:
Sometimes it is hard to start with current library. you may encounter bad configuration related to the provider you are trying to use. in that case an exception is thrown with minimal explanation "Unknown Provider"
Fix:
The message exception is enriched with adapter missing.

Enhance unfound provider exception message to ease troubleshooting

---

composer.json
phpunit.xml
tests/Provider/KeycloakTest.php
tests/Storage/SessionTest.php
tests/User/ActivityTest.php
tests/User/ContactTest.php
tests/User/ProfileTest.php

| Fixed Issues?            | 1246 
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
Added latest PHPUnit and fixed failing tests under it while maintaining compatibility with PHPUnit 8

Added latest PHPUnit and fixed failing tests under it

---

src/Provider/TwitchTV.php

Twitch supports OpenID Connect
| Fixed Issues?            | `Fixes #1438`
Twitch supports OpenID Connect

fixed #1438
